#!/bin/sh

if [ ! -s /etc/mesos/zk ];
then
  echo "/etc/mesos/zk not found or empty"
  exit 0
fi

if [ ! -s /etc/mesos/mesos-master ];
then
  echo "/etc/mesos/mesos-master not found or empty"
  exit 0
fi

if [ ! -s /etc/mesos/etcd ];
then
  echo "/etc/mesos/etcd not found or empty"
  exit 0
fi

sv restart kube-apiserver
